package commands

import commandslist "github.com/AntoineMeresse/flibot-urt/src/commands/commands_list"

var Commands = map[string]Command{
	// Level: 0
	"play":       {Function: commandslist.Play, excludeFromBridge: true},
	"spec":       {Function: commandslist.Spec, excludeFromGuess: true, excludeFromBridge: true},
	"currentmap": {Function: commandslist.CurrentMap},
	"setnextmap": {Function: commandslist.SetNextMap, Usage: "!setnextmap [search] [index]"},
	"roll":       {Function: commandslist.Roll},
	"nextmap":    {Function: commandslist.NextMap},
	"stamina":    {Function: commandslist.Stamina},
	"ready":      {Function: commandslist.Ready, Usage: "!ready", excludeFromGuess: true},
	"goto":       {Function: commandslist.Goto, Usage: "!goto"},
	"invisible":  {Function: commandslist.Invisible, Usage: "!invisible"},
	"loadonce":   {Function: commandslist.Loadonce, Usage: "!loadonce"},
	"map":        {Function: commandslist.ChangeMap, Usage: "!map [search] [index] (-f)", excludeFromGuess: true},
	"maps":       {Function: commandslist.MapList, Usage: "!maps"},
	"callvote":   {Function: commandslist.Callvote, Usage: "!callvote tocomplete"},
	"+":          {Function: commandslist.VoteYes, excludeFromGuess: true},
	"-":          {Function: commandslist.VoteNo, excludeFromGuess: true},
	"help":       {Function: commandslist.Help},
	"mapinfo":    {Function: commandslist.MapInformation},
	"topruns":    {Function: commandslist.ToprunsInformation},
	"serverruns": {Function: commandslist.ServerRuns, Usage: "!serverruns [map]"},
	"ahead":      {Function: commandslist.Ahead, Usage: "!ahead [map]"},
	"missing":    {Function: commandslist.Missing, Usage: "!missing [maxlvl]"},
	"similar":    {Function: commandslist.Similar, Usage: "!similar [map]"},
	"coin":       {Function: commandslist.Coin, Usage: "!coin", forceGlobal: true},
	"cyclemap":   {Function: commandslist.CycleMap, Usage: "!cyclemap (-f)"},
	"top":        {Function: commandslist.TopInformation},
	"latestruns": {Function: commandslist.LatestRuns},
	"latestmaps": {Function: commandslist.LatestMaps},
	"birthday":   {Function: commandslist.Birthday},
	"bounties":   {Function: commandslist.Bounties},
	"pen":        {Function: commandslist.Pen},
	"potd":       {Function: commandslist.PenOfTheDay},
	"phof":       {Function: commandslist.PenHallOfFame},
	"phos":       {Function: commandslist.PenHallOfShame},
	"pb":         {Function: commandslist.PersonalBest},
	"aliases":    {Function: commandslist.Aliases, Level: 20, Usage: "!aliases [player]"},
	"ignore":     {Function: commandslist.Ignore, Usage: "!ignore [player]"},
	"unignore":   {Function: commandslist.Unignore, Usage: "!unignore [id]"},
	"compare":    {Function: commandslist.Compare, Usage: "!compare [-list | 1-10 [1-10] [1-10]]"},
	"time":       {Function: commandslist.Time, Usage: "!time"},
	"tp":         {Function: commandslist.Tp, Usage: "!tp [player]", excludeFromGuess: true},
	"status":     {Function: commandslist.ServerStatus, Usage: "!status [p(layers)/e(mpty)]"},
	"quit":       {Function: commandslist.Quit, Usage: "!quit [reason]"},
	"admins":     {Function: commandslist.Admins, Usage: "!admins"},
	"level":      {Function: commandslist.Level, Usage: "!level"},
	"locate":     {Function: commandslist.Locate, Usage: "!locate [player]"},
	"website":    {Function: commandslist.Website, Usage: "!website"},
	"discord":    {Function: commandslist.Discord, Usage: "!discord"},
	"quote":      {Function: commandslist.Quote, Usage: "!quote [id]", forceGlobal: true},
	"findquote":  {Function: commandslist.FindQuote, Usage: "!findquote [text]"},
	"all":        {Function: commandslist.All, Usage: "!all [message]"},
	"trad":       {Function: commandslist.Trad, Usage: "!trad [message]", excludeFromBridge: true},
	"tradto":     {Function: commandslist.TradTo, Usage: "!tradto [lang] [message]", excludeFromBridge: true},
	"extend":     {Function: commandslist.Extend, Usage: "!extend or !extend [1-999]"},
	"redo":       {Function: commandslist.Redo, Usage: "!redo [extra params]"},

	// Level: 40
	"afk":        {Function: commandslist.Afk, Level: 40, Usage: "!afk [playerId/Name] (-f)", excludeFromGuess: true},
	"nuke":       {Function: commandslist.Nuke, Level: 40, Usage: "!nuke [playerId/Name]"},
	"veto":       {Function: commandslist.VoteVeto, Level: 40, Usage: "!veto"},

	// Level: 60
	"slap":       		{Function: commandslist.Slap, Level: 60, Usage: "!slap [playerId/Name] (-f)", excludeFromGuess: true},
	"setgoto":          {Function: commandslist.SetGoto, Level: 60},
	"removegoto":       {Function: commandslist.RemoveGoto, Level: 60},
	"force":            {Function: commandslist.Force, Level: 60, Usage: "!force [player] [red/blue/spectator/free] (-f)", excludeFromGuess: true},
	"mapget":           {Function: commandslist.MapGet, Level: 60},
	"mapremove":        {Function: commandslist.MapRemove, Level: 60},
	"timelimit":        {Function: commandslist.Timelimit, Level: 60, Usage: "!timelimit [1-999]"},
	"putgroup":         {Function: commandslist.SetRights, Level: 60, Usage: "!putgroup [player] [-1 to 100]"},

	// Level : 80
	"kick":             {Function: commandslist.Kick, Level: 80, Usage: "!kick [playerId/Name] [reason] (-f)", excludeFromGuess: true},
	"moveplayer":       {Function: commandslist.MovePlayer, Level: 80, Usage: "!moveplayer [player1] [player2] (-f)"},
	"mute":             {Function: commandslist.Mute, Level: 80, Usage: "!mute [playerId/Name]"},
	"addquote":         {Function: commandslist.AddQuote, Level: 80, Usage: "!addquote [text]"},
	"removequote":      {Function: commandslist.RemoveQuote, Level: 80, Usage: "!removequote [id]"},
	"portgotos":        {Function: commandslist.PortGotos, Level: 80, Usage: "!portgotos [sourcemap]"},
	"portmapoptions":   {Function: commandslist.PortMapOptions, Level: 80, Usage: "!portmapoptions [sourcemap]"},
	"overbounces":      {Function: commandslist.Overbounces, Level: 80, Usage: "!overbounces [0 or 1]"},
	"setmapoptions":    {Function: commandslist.SetMapOptions, Level: 80, Usage: "!setmapoptions [opt1, opt2, ...]"},
	"resetoptions":     {Function: commandslist.ResetOptions, Level: 80, Usage: "!resetoptions"},
	"mapoptions":       {Function: commandslist.MapOptions, Level: 80, Usage: "!mapoptions"},
	"removemapoptions": {Function: commandslist.RemoveMapOptions, Level: 80, Usage: "!removemapoptions"},

	// Level: 90
	"ban":        {Function: commandslist.Ban, Level: 90, Usage: "!ban [playerId/Name/@dbId] [reason]", excludeFromGuess: true},
	"unban":      {Function: commandslist.Unban, Level: 90, Usage: "!unban [@dbId/banId]", excludeFromGuess: true},
	"lookup":     {Function: commandslist.Lookup, Level: 90, Usage: "!lookup [name/alias] or !lookup @[id]"},
	"resetgotos": {Function: commandslist.ResetGotos, Level: 90, Usage: "!resetgotos [map] (-f)"},

	// Level: 100
	"pencoin":      {Function: commandslist.PenCoin, Level: 100, Usage: "!pencoin [player]"},
	"resetpencoin": {Function: commandslist.ResetPenCoin, Level: 100, Usage: "!resetpencoin [amount]",  excludeFromBridge: true},
	"password": {Function: commandslist.Password, Level: 100, Usage: "!password [password]"},
	"rcon":     {Function: commandslist.Rcon, Level: 100, Usage: "!rcon [command]", excludeFromGuess: true, forcePM: true},
	"playerid":   {Function: commandslist.PlayerId, Level: 100, Usage: "!playerid [id]"},
	"globalpen": {Function: commandslist.GlobalPen, Level: 100, Usage: "!globalpen", excludeFromBridge: true},

	// Dev Only
	"healthcheck": {Function: commandslist.HealthCheck, Level: 100, Usage: "!healthcheck", forcePM: true},
	"players":     {Function: commandslist.PlayersList, Level: 100, Usage: "!players", excludeFromBridge: true, forcePM: true},
	"player":      {Function: commandslist.PlayersGet, Level: 100, Usage: "!player", excludeFromBridge: true, forcePM: true},
	"runs":        {Function: commandslist.RunsDescribe, Level: 100, Usage: "!runs", excludeFromBridge: true, forcePM: true},
	"runshistory": {Function: commandslist.RunsHistory, Level: 100, Usage: "!runshistory", excludeFromBridge: true, forcePM: true},
}

var Alias = map[string]string{
	"cycle":         "cyclemap",
	"pl":            "play",
	"sp":            "spec",
	"rmgoto":        "removegoto",
	"invi":          "invisible",
	"lo":            "loadonce",
	"download":      "mapget",
	"mg":            "mapget",
	"mget":          "mapget",
	"dl":            "mapget",
	"cv":            "callvote",
	"current":       "currentmap",
	"mapinfos":      "mapinfo",
	"mi":            "mapinfo",
	"info":          "mapinfo",
	"tr":            "topruns",
	"above":         "ahead",
	"flip":          "coin",
	"sruns":         "serverruns",
	"sr":            "serverruns",
	"latest":        "latestruns",
	"lr":            "latestruns",
	"lm":            "latestmaps",
	"snm":           "setnextmap",
	"mremove":       "mapremove",
	"mrm":           "mapremove",
	"g_overbounces": "overbounces",
	"ob":            "overbounces",
	"pcoin":         "pencoin",
	"h":             "help",
	"alias":         "aliases",
	"l":             "lookup",
	"rh":            "runshistory",
	"ff":            "quit",
	"site":          "website",
	"rights":        "putgroup",
	"mo":            "mapoptions",
	"smo":           "setmapoptions",
	"rmmo":          "removemapoptions",
	"lvl": 			 "level",
	"cp":            "compare",
	"lcmd":          "redo",
	"lc":            "redo",
}
