package commands

import commandslist "github.com/AntoineMeresse/flibot-urt/src/commands/commands_list"

var Commands map[string]Command = map[string]Command{
	// Level: 0
	"play":       {commandslist.Play, 0, "", true},
	"spec":       {commandslist.Spec, 0, "", true},
	"currentmap": {commandslist.CurrentMap, 0, "", true},
	"setnextmap": {commandslist.SetNextMap, 0, "", true},
	"nextmap":    {commandslist.NextMap, 0, "", true},
	"stamina":    {commandslist.Stamina, 0, "", true},
	"ready":      {commandslist.Ready, 0, "!ready", true},
	"goto":       {commandslist.Goto, 0, "!goto", true},
	"invisible":  {commandslist.Invisible, 0, "!invisible", true},
	"loadonce":   {commandslist.Loadonce, 0, "!loadonce", true},
	"map":        {commandslist.MapFn, 0, "!map [search]", true},
	"maps":       {commandslist.MapList, 0, "!maps", true},
	"callvote":   {commandslist.Callvote, 0, "!callvote tocomplete", true},
	"+":          {commandslist.VoteYes, 0, "", true},
	"-":          {commandslist.VoteNo, 0, "", true},
	"help":       {commandslist.Help, 0, "", true},
	"mapinfo":    {commandslist.MapInformation, 0, "", true},
	"topruns":    {commandslist.ToprunsInformation, 0, "", true},
	"top":        {commandslist.TopInformation, 0, "", true},
	"latestruns": {commandslist.LatestRuns, 0, "", true},
	"latestmaps": {commandslist.LatestMaps, 0, "", true},
	"pen":        {commandslist.Pen, 0, "", true},
	"potd":       {commandslist.PenOfTheDay, 0, "", true},
	"phof":       {commandslist.PenHallOfFame, 0, "", true},
	"phos":       {commandslist.PenHallOfShame, 0, "", true},
	"pb":         {commandslist.PersonnalBest, 0, "", true},
	"status":     {commandslist.ServerStatus, 0, "!status", true},
	"quit":       {commandslist.Quit, 0, "!quit", true},
	"register":   {commandslist.Register, 0, "!register", true},

	"afk": {commandslist.Afk, 20, "!afk [playerId/Name]", true},

	// Level: 80
	"setgoto":     {commandslist.SetGoto, 0, "", true},
	"removegoto":  {commandslist.RemoveGoto, 80, "", true},
	"mapget":      {commandslist.MapGet, 80, "", true},
	"mapremove":   {commandslist.MapRemove, 80, "", true},
	"timelimit":   {commandslist.Timelimit, 80, "!timelimit [1-999]", true},
	"extend":      {commandslist.Extend, 80, "!extend or !extend [1-999]", true},
	"veto":        {commandslist.VoteVeto, 80, "!veto", true},
	"overbounces": {commandslist.Overbounces, 80, "!overbounces [0 or 1]", true},

	// Dev Only
	"players": {commandslist.PlayersList, 0, "!players", false},
	"player":  {commandslist.PlayersGet, 0, "!player", false},
}

var CommandsAlias map[string]string = map[string]string{
	"pl":            "play",
	"sp":            "spec",
	"rmgoto":        "removegoto",
	"invi":          "invisible",
	"l1":            "loadonce",
	"lo":            "loadonce",
	"download":      "mapget",
	"mg":            "mapget",
	"mget":          "mapget",
	"dl":            "mapget",
	"cv":            "callvote",
	"current":       "currentmap",
	"mapinfos":      "mapinfo",
	"mi":            "mapinfo",
	"tr":            "topruns",
	"latest":        "latestruns",
	"lr":            "latestruns",
	"lm":            "latestmaps",
	"snm":           "setnextmap",
	"mremove":       "mapremove",
	"mrm":           "mapremove",
	"g_overbounces": "overbounces",
	"ob":            "overbounces",
	"ff":            "quit",
	"h":             "help",
}
