package commands

import commandslist "github.com/AntoineMeresse/flibot-urt/src/commands/commands_list"

var Commands = map[string]Command{
	// Level: 0
	"play":       {Function: commandslist.Play},
	"spec":       {Function: commandslist.Spec, excludeFromGuess: true},
	"currentmap": {Function: commandslist.CurrentMap},
	"setnextmap": {Function: commandslist.SetNextMap},
	"roll":       {Function: commandslist.Roll},
	"nextmap":    {Function: commandslist.NextMap},
	"stamina":    {Function: commandslist.Stamina},
	"ready":      {Function: commandslist.Ready, Usage: "!ready", excludeFromGuess: true},
	"goto":       {Function: commandslist.Goto, Usage: "!goto"},
	"invisible":  {Function: commandslist.Invisible, Usage: "!invisible"},
	"loadonce":   {Function: commandslist.Loadonce, Usage: "!loadonce"},
	"map":        {Function: commandslist.MapFn, Usage: "!map [search]", excludeFromGuess: true},
	"maps":       {Function: commandslist.MapList, Usage: "!maps"},
	"callvote":   {Function: commandslist.Callvote, Usage: "!callvote tocomplete"},
	"+":          {Function: commandslist.VoteYes, excludeFromGuess: true},
	"-":          {Function: commandslist.VoteNo, excludeFromGuess: true},
	"help":       {Function: commandslist.Help},
	"mapinfo":    {Function: commandslist.MapInformation},
	"topruns":    {Function: commandslist.ToprunsInformation},
	"serverruns": {Function: commandslist.ServerRuns, Usage: "!serverruns [map]"},
	"ahead":      {Function: commandslist.Ahead, Usage: "!ahead [map]"},
	"missing":    {Function: commandslist.Missing, Usage: "!missing [maxlvl]"},
	"similar":    {Function: commandslist.Similar, Usage: "!similar [map]"},
	"coin":       {Function: commandslist.Coin, Usage: "!coin"},
	"top":        {Function: commandslist.TopInformation},
	"latestruns": {Function: commandslist.LatestRuns},
	"latestmaps": {Function: commandslist.LatestMaps},
	"birthday":   {Function: commandslist.Birthday},
	"bounties":   {Function: commandslist.Bounties},
	"pen":        {Function: commandslist.Pen},
	"potd":       {Function: commandslist.PenOfTheDay},
	"phof":       {Function: commandslist.PenHallOfFame},
	"phos":       {Function: commandslist.PenHallOfShame},
	"pb":         {Function: commandslist.PersonalBest},
	"aliases":    {Function: commandslist.Aliases, Level: 20, Usage: "!aliases [player]"},
	"ignore":     {Function: commandslist.Ignore, Usage: "!ignore [player]"},
	"unignore":   {Function: commandslist.Unignore, Usage: "!unignore [id]"},
	"cp":         {Function: commandslist.Cp, Usage: "!cp"},
	"time":       {Function: commandslist.Time, Usage: "!time"},
	"tp":         {Function: commandslist.Tp, Usage: "!tp [player]", excludeFromGuess: true},
	"status":     {Function: commandslist.ServerStatus, Usage: "!status"},
	"quit":       {Function: commandslist.Quit, Usage: "!quit [reason]"},
	"admins":     {Function: commandslist.Admins, Usage: "!admins"},
	"website":    {Function: commandslist.Website, Usage: "!website"},
	"discord":    {Function: commandslist.Discord, Usage: "!discord"},
	"quote":      {Function: commandslist.Quote, Usage: "!quote"},

	// Level: 40
	"afk": {Function: commandslist.Afk, Level: 40, Usage: "!afk [playerId/Name]", excludeFromGuess: true},

	// Level: 60-80
	"setgoto":          {Function: commandslist.SetGoto, Level: 60},
	"force":            {Function: commandslist.Force, Level: 60, Usage: "!force [player] [red/blue/spectator/free]", excludeFromGuess: true},
	"kick":             {Function: commandslist.Kick, Level: 80, Usage: "!kick [playerId/Name] [reason]", excludeFromGuess: true},
	"moveplayer":       {Function: commandslist.MovePlayer, Level: 80, Usage: "!moveplayer [player1] [player2]"},
	"mute":             {Function: commandslist.Mute, Level: 80, Usage: "!mute [playerId/Name]"},
	"addquote":         {Function: commandslist.AddQuote, Level: 80, Usage: "!addquote [text]"},
	"portgotos":        {Function: commandslist.PortGotos, Level: 80, Usage: "!portgotos [sourcemap]"},
	"portmapoptions":   {Function: commandslist.PortMapOptions, Level: 80, Usage: "!portmapoptions [sourcemap]"},
	"removegoto":       {Function: commandslist.RemoveGoto, Level: 80},
	"mapget":           {Function: commandslist.MapGet, Level: 80},
	"mapremove":        {Function: commandslist.MapRemove, Level: 80},
	"timelimit":        {Function: commandslist.Timelimit, Level: 80, Usage: "!timelimit [1-999]"},
	"extend":           {Function: commandslist.Extend, Level: 80, Usage: "!extend or !extend [1-999]"},
	"veto":             {Function: commandslist.VoteVeto, Level: 80, Usage: "!veto"},
	"overbounces":      {Function: commandslist.Overbounces, Level: 80, Usage: "!overbounces [0 or 1]"},
	"putgroup":         {Function: commandslist.SetRights, Usage: "!putgroup [player] [0-100]"},
	"setmapoptions":    {Function: commandslist.SetMapOptions, Level: 80, Usage: "!setmapoptions [opt1, opt2, ...]"},
	"resetoptions":     {Function: commandslist.ResetOptions, Level: 80, Usage: "!resetoptions"},
	"mapoptions":       {Function: commandslist.MapOptions, Level: 80, Usage: "!mapoptions"},
	"removemapoptions": {Function: commandslist.RemoveMapOptions, Level: 80, Usage: "!removemapoptions"},

	// Level: 90
	"nuke":       {Function: commandslist.Nuke, Level: 90, Usage: "!nuke [playerId/Name]"},
	"slap":       {Function: commandslist.Slap, Level: 90, Usage: "!slap [playerId/Name]", excludeFromGuess: true},
	"ban":        {Function: commandslist.Ban, Level: 90, Usage: "!ban [playerId/Name] [reason]", excludeFromGuess: true},
	"unban":      {Function: commandslist.Unban, Level: 90, Usage: "!unban [id]", excludeFromGuess: true},
	"lookup":     {Function: commandslist.Lookup, Level: 90, Usage: "!lookup [name/alias]"},
	"playerid":   {Function: commandslist.PlayerId, Level: 99, Usage: "!playerid [id]"},
	"resetgotos": {Function: commandslist.ResetGotos, Level: 90, Usage: "!resetgotos [map] (-f)"},

	// Level: 100
	"pencoin":  {Function: commandslist.PenCoin, Level: 100, Usage: "!pencoin [player]"},
	"password": {Function: commandslist.Password, Level: 100, Usage: "!password [password]"},
	"rcon":     {Function: commandslist.Rcon, Level: 100, Usage: "!rcon [command]", excludeFromGuess: true},

	// Dev Only
	"healthcheck": {Function: commandslist.HealthCheck, Level: 100, Usage: "!healthcheck"},
	"players":     {Function: commandslist.PlayersList, Level: 90, Usage: "!players", excludeFromBridge: true},
	"player":      {Function: commandslist.PlayersGet, Level: 90, Usage: "!player", excludeFromBridge: true},
	"runs":        {Function: commandslist.RunsDescribe, Level: 90, Usage: "!runs", excludeFromBridge: true},
	"runshistory": {Function: commandslist.RunsHistory, Level: 90, Usage: "!runshistory", excludeFromBridge: true},
}

var Alias = map[string]string{
	"pl":            "play",
	"sp":            "spec",
	"rmgoto":        "removegoto",
	"invi":          "invisible",
	"lo":            "loadonce",
	"download":      "mapget",
	"mg":            "mapget",
	"mget":          "mapget",
	"dl":            "mapget",
	"cv":            "callvote",
	"current":       "currentmap",
	"mapinfos":      "mapinfo",
	"mi":            "mapinfo",
	"info":          "mapinfo",
	"tr":            "topruns",
	"above":         "ahead",
	"flip":          "coin",
	"sruns":         "serverruns",
	"sr":            "serverruns",
	"latest":        "latestruns",
	"lr":            "latestruns",
	"lm":            "latestmaps",
	"snm":           "setnextmap",
	"mremove":       "mapremove",
	"mrm":           "mapremove",
	"g_overbounces": "overbounces",
	"ob":            "overbounces",
	"pcoin":         "pencoin",
	"h":             "help",
	"alias":         "aliases",
	"rh":            "runshistory",
	"ff":            "quit",
	"site":          "website",
	"rights":        "putgroup",
	"mo":            "mapoptions",
	"smo":           "setmapoptions",
	"rmmo":          "removemapoptions",
}
